### ISSUE TITLE
Search does not work in Ubuntu Touch

### ISSUE THREAD

**Issue by jonnius** [rinigus/pure-maps#368]
Search for addresses does not work anymore (at least since 1.26.1). API keys are installed. This is what I see in the logs:

```
Cannot convert: QVariant(std::nullptr_t, (nullptr))
GET http://photon.komoot.de/api/?q=SChwanseestr.+83+weimar&limit=10&lang=de
Establishing connection to photon.komoot.de
GET failed: gaierror: [Errno -3] Temporary failure in name resolution
Geocoding failed:
Traceback (most recent call last):
  File "/opt/click.ubuntu.com/pure-maps.jonnius/1.26.1.1/share/pure-maps.jonnius/poor/geocoder.py", line 141, in geocode
    results = self._provider.geocode(query=query, x=x, y=y, params=params)
  File "/opt/click.ubuntu.com/pure-maps.jonnius/1.26.1.1/share/pure-maps.jonnius/geocoders/photon.py", line 54, in geocode
    results = poor.http.get_json(url)["features"]
  File "/opt/click.ubuntu.com/pure-maps.jonnius/1.26.1.1/share/pure-maps.jonnius/poor/http.py", line 237, in get_json
    headers=headers)
  File "/opt/click.ubuntu.com/pure-maps.jonnius/1.26.1.1/share/pure-maps.jonnius/poor/http.py", line 327, in _request_json
    text = _request(method, url, body, encoding, retry, headers)
  File "/opt/click.ubuntu.com/pure-maps.jonnius/1.26.1.1/share/pure-maps.jonnius/poor/http.py", line 259, in _request
    encoding=encoding, retry=retry, headers=headers)
  File "/opt/click.ubuntu.com/pure-maps.jonnius/1.26.1.1/share/pure-maps.jonnius/poor/http.py", line 213, in request
    if 'exception' in result: raise result['exception']
  File "/opt/click.ubuntu.com/pure-maps.jonnius/1.26.1.1/share/pure-maps.jonnius/poor/http.py", line 169, in _request_worker
    headers=task['headers'])
  File "/opt/click.ubuntu.com/pure-maps.jonnius/1.26.1.1/share/pure-maps.jonnius/poor/http.py", line 287, in _request_real
    connection.request(method, path, body, headers=headall)
  File "/usr/lib/python3.5/http/client.py", line 1122, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1167, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1118, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 944, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 887, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 859, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by jonnius** [comment]
It does work with the same version in the Clickable desktop mode.

**Comment by rinigus** [comment]
Photon had some issues lately. Right now it works from here. Check bit later again. Also try to search in search box at http://photon.komoot.de/ (Try me...) to be sure its not service issue.

**Comment by jonnius** [comment]
It seems you are right. It works now.
